export { default as Header } from 'components/Header'
export { default as BlockWithFish } from 'components/BlockWithFish'
export { default as TextWithButton } from 'components/TextWithButtonAnimation'
export { default as TextWithButtonAndImage } from 'components/TextWithButtonAndImage'
export { default as Layout } from 'components/Layout'
export { default as OrderBlock } from 'components/OrderBlock'
export { default as Modal } from 'components/Modal'
export { default as Carousel } from 'components/Carousel'
export { default as Advantages } from 'components/Advantages'
export { default as Footer } from 'components/Footer'
export { Delivery } from 'components/Blocks'
export { default as Menu } from 'components/Menu'
