export { default as Header } from 'mobileComponents/Header'
export { default as BlockWithFish } from 'mobileComponents/BlockWithFish'
export { default as TextWithButton } from 'mobileComponents/TextWithButtonAnimation'
export { default as TextWithButtonAndImage } from 'mobileComponents/TextWithButtonAndImage'
export { default as Layout } from 'mobileComponents/Layout'
export { default as OrderBlock } from 'mobileComponents/OrderBlock'
export { default as Modal } from 'mobileComponents/Modal'
export { default as Carousel } from 'mobileComponents/Carousel'
export { default as Advantages } from 'mobileComponents/Advantages'
export { default as Footer } from 'mobileComponents/Footer'
export { Delivery } from 'mobileComponents/Blocks'
export { default as Menu } from 'mobileComponents/Menu'
